version: "3.7"

services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    ports:
      - 10000:3000
    volumes:
      - /home/chuck/data/metabase:/metabase-data

