version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    expose:
      - 3000
    volumes:
      - /home/chuck/data/grafana/data:/var/lib/grafana
      - /home/chuck/data/grafana/config:/etc/grafana
    networks:
      - web
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:grafana.choukalos.org"

networks:
  web:
    external: true
