version: '2.0'

services:
  cadvisor:
    privileged: true
    image: google/cadvisor:latest
    restart: always
    volumes:
      - /var/lib/docker:/var/lib/docker:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
    ports:
      - 9080:8080

