version: '3.4'

services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name:  minecraftbedrockserver
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      SERVER_NAME: "The Flintstones"
      OPS: "DyELaN123"
      MAX_PLAYERS: 6
      MAX_THREADS: 1
    networks:
      - minecraft
    ports:
      - "19132:19132/udp"
    volumes:
      - /home/chuck/data/minecraftbedrock:/data
    stdin_open: true
    tty: true
    deploy:
      resources:
         limits:
           cpus: '0.5 '
           memory: 1000M


networks:
  minecraft:
    driver: bridge


