# Run once per day at 10pm to check and update docker images
version: '3'
services:
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command:  --schedule "0 22 * * *"



