version: '3.4'

services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      SERVER_NAME: "Peanutsville"
      MAX_PLAYERS: 10
      MAX_THREADS: 2
    networks:
      - minecraft
    ports:
      - "25565:25565"
    volumes:
      - /home/chuck/data/minecraftjava:/data
    stdin_open: true
    tty: true
    deploy:
      resources:
         limits:
           cpus: '1.0'
           memory: 2000M

networks:
  minecraft:
    driver: bridge


