--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mine-xmr-deployment
  labels:
    app: mine-xmr
spec: 
  replicas: 8
  selector: 
    matchLabels: 
      app: mine-xmr
  template: 
    metadata: 
      labels: 
        app: mine-xmr
    spec: 
      containers: 
        - name:  mine-xmr
          image:  choukalos/alpine-xmrig:latest
          imagePullPolicy:  Always
          command: 
            - ./xmrig
            - --donate-level
            - '1'
            - --max-cpu-usage
            - '95'
            - -o
            - 'monerohash.com:2222'
            - -u
            - 48XhYHerxvcREeucZyg5uGiP5gw4buYS4PAMBvADgq7HE62hjFJLa1Rh37f4Gx7FkBPdmEBrErebhC9RBv6i3ckrSwew4rN 
            - -p
            - x
            - -k
          resources: 
            limits: 
              cpu: 1.0
              memory: 100Mi

