global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    # defaults to HTTP scheme with metrics_path /metrics 
    static_configs:
      - targets: ['192.168.1.51:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.1.51:9080','192.168.1.110:9080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.1.51:9100','192.168.1.52:9100','192.168.1.53:9100','192.168.1.110:9100']

  - job_name: 'mino'
    metrics_path: /minio/prometheus/metrics
    scheme: http
    static_configs:
      - targets: ['192.168.1.110:9000']

  - job_name: 'snmp'
    static_configs:
      - targets: ['192.168.1.1']
    metrics_path: /snmp
    params:
      module: [ubiquiti_edgemax]
      community: [public]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116
  
  # job needed:  Traefik

