version: "3.7"
services:
  timemachine:
    image:  odarriba/timemachine
    container_name: "timemachine"
    restart: always
    ports:
      - "548:548"
      - "636:636"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    volumes:
      - /mnt/timemachine:/timemachine
      - type: bind
        source: /home/chuck/data/timemachine/entrypoint.sh
        target: /entrypoint.sh
    deploy:
      resources:
         limits:
            cpus: '0.5'
            memory: 1000M

networks:
  default:
    driver: bridge

