version: "3.7"

services:
  timemachine:
    image:  dperson/samba
    container_name: "timemachine"
    restart: unless-stopped
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    volumes:
      - /mnt/timemachine/chuckpro:/mnt:z
      - /mnt/timemachine/mpro:/mnt2:z
      - /mnt/timemachine/imac:/mnt3:z
      - /mnt/timemachine/chuckbook:/mnt4:z
    command: '-s "chuckpro;/mnt;yes;no;no;timemachine" -s "mpro;/mnt2;yes;no;no;timemachine" -s "imac;/mnt3;yes;no;no;timemachine" -s "chuckbook;/mnt4;yes;no;no;timemachine" -u "timemachine;backup" -p'
    deploy:
      resources:
         limits:
            cpus: '0.5'
            memory: 512M

networks:
  default:
    driver: bridge

